init_config:

instances:
  - min_collection_interval: 10
    detailed_mode: true

logs_enabled: true

apm_config:
  enabled: true
  log_file: /var/log/datadog/trace-agent.log
  apm_non_local_traffic: true

process_config:
  enabled: true
  intervals:
    process_realtime: 10
    process: 30

logs_config:
  container_collect_all: true
  logs_dd_url: intake.logs.datadoghq.com
  logs_no_ssl: false

# Application Performance Monitoring
custom_checks:
  - name: api_health
    command: "curl -f http://localhost:443/health"
    interval: 30

# Resource Monitoring
system_probe_config:
  enabled: true
  sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock

# Metrics Collection
dogstatsd_mapper_profiles:
  - name: node_metrics
    prefix: "node."
    mappings:
      - match: "process.memory.*"
        name: "memory"
        tags:
          type: "$1"
      - match: "process.cpu.*"
        name: "cpu"
        tags:
          type: "$1"

# Alert Configuration
monitors:
  - name: "High Error Rate"
    type: "metric alert"
    query: "avg(last_5m):sum:trace.http.request.errors{env:production} / sum:trace.http.request.hits{env:production} > 0.01"
    message: "Error rate exceeded 1% threshold"
    
  - name: "High API Latency"
    type: "metric alert"
    query: "avg(last_5m):avg:trace.http.request.duration{env:production} > 1000"
    message: "API latency exceeded 1s threshold"
    
  - name: "High Memory Usage"
    type: "metric alert"
    query: "avg(last_5m):system.mem.used{env:production} / system.mem.total{env:production} * 100 > 90"
    message: "Memory usage exceeded 90% threshold" 