name: Template Verification

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run verification scripts
      run: |
        npm run fix-docs
        npm run update-timestamps
        npm run check-docs
        npm run check-references
        npm run find-duplicates
    
    - name: Run tests
      run: npm test
    
    - name: Check for documentation changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
    
    - name: Create Pull Request
      if: steps.git-check.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'docs: Update documentation from verification scripts'
        commit-message: 'docs: Update documentation from verification scripts'
        branch: automated-doc-updates
        delete-branch: true
        body: |
          Automated documentation updates from verification scripts.
          
          - Fixed documentation issues
          - Updated timestamps
          - Verified references
          - Checked for duplicates 